### ISSUE TITLE
Add blog posts #tags

### ISSUE THREAD

**Issue by OPerel** [wonderfloyd/Hackathon-Corona#35]
This task requires both modifications to the code and to Contentful's _Content model_.
In Contentful's dashboard, the user should be able add tags, to which he can later link his blog posts.
When adding a blog post in Contentful's dashboard, the user should have the option to link one or more tags to his post.

If a blog post has tags linked to it, all of the tags names should be displayed both in the post's index list item and in the post's page.
Each tag's name should be a link leading to a page listing all the blog posts linked to the current tag.

Note: Please document any set up and configuration changes made from the initial set up in `README.md`.

**Comment by ivorco** [comment]
I assumed the best way to add tags was to add another "table to the database", which in our case is another content type added to the content model.
So I created the tag content model with a property tagName, and added a tag to two of my blog entries.
However, when I get the tags field from Contentful I get something like this:
> [{"sys":{"type":"Link","linkType":"Entry","id":"51NzmBX6Ku38tuF6eq1ykm"}}]

So I think I need to somehow connect the data together here:
> const allPosts = await fetch(`${baseUrl}/spaces/${spaceId}/environments/${environmentId}/entries?access_token=${accessToken}`);
> const posts = await allPosts.json();

I can easily get all tags but I'm not sure how to connect the tags to the posts, or if I need to at all

**Comment by OPerel** [comment]
Hey @ivorco,
Take a look at [this](https://www.contentful.com/developers/docs/concepts/links/) from the Contentful docs.
Hope this helps.

**Comment by ivorco** [comment]
So it seems that Contentful retrieves *all* entries when calling the API, which means that it retrieves tags as well, but not linked to the posts but on the same level.
I checked and it seems that the search filtering hid this issue, so I will have to implement filtering to posts only, and get each tag by id manually.

**Comment by OPerel** [comment]
I'm re-opening this because tags are not yet implemented on the individual post pages

**Comment by ivorco** [comment]
> I'm re-opening this because tags are not yet implemented on the individual post pages
Yepp, this is the next issue I want to tackle

**Comment by ivorco** [comment]
@OPerel Can you look at branch or-#35tags?
For some reason I can load tag names correctly sometimes.

**Comment by OPerel** [comment]
This issue is still open as tags should be links to an index of all posts with that tag.
