### ISSUE TITLE
Add auto generated blog post excerpt

### ISSUE THREAD

**Issue by OPerel** [wonderfloyd/Hackathon-Corona#36]
_Current behavior:_ The excerpt has to be manually inserted by the user when creating the post.
_Expected behavior:_ The excerpt should be automatically generated from the beginning of the post's body.

**Comment by orc886** [comment]
Should we save the excerpt back to **Contentful**?
Should we always generate an excerpt? Or just when there is none from **Contentful**?

**Comment by OPerel** [comment]
Every blog post is suppose to have an excerpt, and the user should never insert it manually.
So there are few approaches i can think of:
- you can look in Contentful's docs if they have something that can provide this.
- you can generate it in code every time it's needed.
- you can generate it in code, and use Contentful's API to save it so it won't have to be generated every time. 

Please ask if something is still not clear

**Comment by orc886** [comment]
Okay, what I think I'll do is to check for an excerpt.
If none exists, I'll generate one, and then save to Contentful.

**Comment by yatuvy** [comment]
cool 👍 
please assign this issue to yourself

**Comment by orc886** [comment]
Bummer

> The Content Delivery API (CDA), available at cdn.contentful.com, is a read-only API for delivering content from Contentful to apps, websites and other media. Content is delivered as JSON data, and images, videos and other media as files.

So question is, should we move from cdn.contentful.com to api.contentful.com which is read/write?

**Comment by OPerel** [comment]
I thought that they have one api for reading and another for writing... So whatever you think is better and more efficient.
I'm going to open an issue for exporting all Contentful API calls to an extarnal service, so you can have that in mind as well

**Comment by orc886** [comment]
I'm not so sure about setting the excerpt through the code
Seems like not a very good UX to do this automatically

Let's check this in as is then I'll move the api calls as specified in #45

**Comment by OPerel** [comment]
Not sure I understood...
You want to assign yourself to https://github.com/wonderfloyd/Hackathon-Corona/issues/45 as well and work on them together?

**Comment by orc886** [comment]
I'm saying that I take back my idea to save it with the api, unless anyone has an idea how to involve the user in the process

**Comment by OPerel** [comment]
why would you want to involve the user? it's suppose to happen automatically. the user only writes the post and the excerpt is generated from it.
the pages are generated on the server at built time so it shouldn't affect UX the first time an excerpt is generated.
but if you're worried about it you can check my first suggestion to look for a solution in Contentful's docs.

**Comment by orc886** [comment]
> If none exists, I'll generate one, and **then save to Contentful**.

I'm talking about that
I realized saving back the data is not the right experiance

**Comment by OPerel** [comment]
> I realized saving back the data is not the right experience

how do you mean? how do you think it will affect the experience?
and do you have any suggestions?

**Comment by orc886** [comment]
> > I realized saving back the data is not the right experience
> 
> how do you mean? how do you think it will affect the experience?
> and do you have any suggestions?

I believe that doing a write action without letting the user know is bad practice
I though about adding the excerpt to the [id].tsx page (it doesn't exist there) and than having a button 'Save auto-generated excerpt' which will do that saving upon user request
Right now there's no excerpt in this page so I'm not sure how much good of an idea is it

**Comment by orc886** [comment]
Like that:
![image](https://user-images.githubusercontent.com/2694823/79138432-2cac4600-7dbd-11ea-85bb-b551185579f3.png)

**Comment by OPerel** [comment]
Closed: PR https://github.com/wonderfloyd/Hackathon-Corona/pull/52
